"""Seed the catalog with real CC-licensed reference data.

Usage:
    python manage.py seed_catalog           # create missing records only
    python manage.py seed_catalog --fresh   # wipe catalog tables first
"""

from datetime import date

from django.core.management.base import BaseCommand

from catalog.models import Artist, Genre, License, Track

# name, url, requires_attribution, description
LICENSES = [
    (
        "NCS License",
        "https://ncs.io/usage-policy",
        True,
        "NoCopyrightSounds usage policy: free for commercial and non-commercial use, monetization allowed, as long as the artist and track are credited (see per-track attribution string) with links back to NCS and the artist.",
    ),
    (
        "CC BY 4.0",
        "https://creativecommons.org/licenses/by/4.0/",
        True,
        "Free to use for any purpose, including commercially, with attribution to the author.",
    ),
    (
        "CC BY 3.0",
        "https://creativecommons.org/licenses/by/3.0/",
        True,
        "Free to use for any purpose with attribution; the version many Free Music Archive artists published under.",
    ),
    (
        "CC BY-SA 4.0",
        "https://creativecommons.org/licenses/by-sa/4.0/",
        True,
        "Free to use with attribution; derivatives must use the same license.",
    ),
    (
        "CC BY-SA 3.0",
        "https://creativecommons.org/licenses/by-sa/3.0/",
        True,
        "Free to use with attribution; derivatives must use the same license (3.0).",
    ),
    (
        "CC0 1.0",
        "https://creativecommons.org/publicdomain/zero/1.0/",
        False,
        "No rights reserved. Free to use for any purpose, no attribution required. (Reference row - no track in this batch uses it yet.)",
    ),
    (
        "CC BY-NC 4.0",
        "https://creativecommons.org/licenses/by-nc/4.0/",
        True,
        "Free to use non-commercially with attribution. (Reference row.)",
    ),
]

# name
GENRES = [
    "Electronic",
    "House",
    "Progressive House",
    "Electro House",
    "Electronic Pop",
    "Trap",
    "Melodic Dubstep",
    "Glitch Hop",
    "Drumstep",
    "Chill",
    "Comedy",
    "Orchestral",
    "Jazz",
    "Rock",
    "Easy Listening",
    "Ambient",
    "Neoclassical",
    "Instrumental Hip-Hop",
    "Funk",
    "Cinematic",
    "Soundtrack",
    "Blues",
    "Folk",
]

# name, dob, bio
ARTISTS = [
    (
        "Alan Walker",
        date(1997, 8, 24),
        "British-Norwegian DJ and producer who rose from early NCS releases (Fade, Spectre, Force) to global stardom.",
    ),
    (
        "Tobu",
        date(1992, 9, 10),
        "Latvian melodic-house producer whose NCS anthems Hope, Candyland and Cloud 9 are among the label's most-used tracks.",
    ),
    (
        "Itro",
        None,
        "Melodic house producer and frequent Tobu collaborator (Cloud 9, Sunburst).",
    ),
    (
        "Cartoon",
        None,
        "Estonian electronic duo (Jeja and Karl); 'On & On' feat. Daniel Levi is one of the most-recognized NCS releases.",
    ),
    (
        "DEAF KEV",
        date(1996, 10, 28),
        "Glitch-hop producer; 'Invincible' remains one of NCS's most iconic releases.",
    ),
    (
        "Janji",
        date(1993, 2, 9),
        "Progressive-house producer known for 'Heroes Tonight' featuring vocalist Johnning.",
    ),
    (
        "Electro-Light",
        None,
        "Electronic producer behind 'Symbolism' and its two-part sequel, The Symbolism Trilogy.",
    ),
    (
        "Disfigure",
        None,
        "Melodic-dubstep project; 'Blank' is a staple of the early NCS catalog.",
    ),
    (
        "Elektronomia",
        None,
        "Producer behind 'Sky High', one of NCS's most-streamed progressive-house tracks.",
    ),
    (
        "Ahrix",
        None,
        "Producer whose 2013 release 'Nova' is one of NCS's earliest viral tracks.",
    ),
    (
        "Different Heaven",
        None,
        "Producer, co-creator of the NCS classic 'My Heart' with EH!DE.",
    ),
    ("EH!DE", None, "Co-producer of the NCS drumstep classic 'My Heart'."),
    (
        "Kovan",
        None,
        "House producer, best known on NCS for 'Skyline' with Electro-Light.",
    ),
    (
        "Kevin MacLeod",
        date(1972, 9, 28),
        "Prolific US composer releasing thousands of instrumental tracks under CC BY via incompetech.com; arguably the most-heard royalty-free composer on the internet.",
    ),
    (
        "Kai Engel",
        date(1992, 9, 4),
        "Moscow-based neoclassical/ambient composer (Anton Fedchenkov); one of the most-downloaded artists on Free Music Archive.",
    ),
    (
        "Broke For Free",
        None,
        "Chill-hop producer from the Free Music Archive; 'Night Owl' is one of the most-used Creative Commons tracks in podcasting.",
    ),
    (
        "Scott Holmes",
        None,
        "UK producer of CC-licensed cinematic and production music for film, TV and media.",
    ),
    (
        "Jahzzar",
        None,
        "Spanish multi-instrumentalist releasing CC-licensed ambient and indie music via the Free Music Archive.",
    ),
    (
        "Lobo Loco",
        date(1968, 2, 26),
        "German blues/folk producer with one of the largest Creative Commons catalogs on the Free Music Archive.",
    ),
]


# title, artist, genres, license, cover, audio_file, duration_seconds, file_size, is_instrumental, is_published, is_private, play_count, attribution
TRACKS = [
    (
        "Fade",
        "Alan Walker",
        ["Progressive House", "Electronic"],
        "NCS License",
        "fade-alan-walker.jpg",
        "fade-alan-walker.mp3",
        264,
        4225148,
        True,
        True,
        False,
        0,
        "Song: Alan Walker - Fade [NCS Release]\nMusic provided by NoCopyrightSounds\nFree Download: http://ncs.io",
    ),
    (
        "Hope",
        "Tobu",
        ["House", "Chill"],
        "NCS License",
        "hope-tobu.jpg",
        "hope-tobu.mp3",
        288,
        6430078,
        True,
        True,
        False,
        0,
        "Song: Tobu - Hope [NCS Release]\nMusic provided by NoCopyrightSounds\nFree Download: http://ncs.io",
    ),
    (
        "Candyland",
        "Tobu",
        ["House", "Electronic"],
        "NCS License",
        "candyland-tobu.jpg",
        "candyland-tobu.mp3",
        201,
        3211179,
        True,
        True,
        False,
        0,
        "Song: Tobu - Candyland [NCS Release]\nMusic provided by NoCopyrightSounds\nFree Download: http://ncs.io",
    ),
    (
        "Cloud 9",
        "Itro",
        ["House", "Chill"],
        "NCS License",
        "cloud-9-itro-tobu.jpg",
        "cloud-9-itro-tobu.mp3",
        278,
        4441651,
        True,
        True,
        False,
        0,
        "Song: Itro & Tobu - Cloud 9 [NCS Release]\nMusic provided by NoCopyrightSounds\nFree Download: http://ncs.io",
    ),
    (
        "On & On",
        "Cartoon",
        ["Electronic Pop"],
        "NCS License",
        "on-and-on-cartoon.jpg",
        "on-and-on-cartoon.mp3",
        208,
        3329599,
        False,
        True,
        False,
        0,
        "Song: Cartoon, Jeja - On & On (feat. Daniel Levi) [NCS Release]\nMusic provided by NoCopyrightSounds\nFree Download: http://ncs.io",
    ),
    (
        "Invincible",
        "DEAF KEV",
        ["Glitch Hop", "Electronic"],
        "NCS License",
        "invincible-deaf-kev.jpg",
        "invincible-deaf-kev.mp3",
        273,
        4371114,
        True,
        True,
        False,
        0,
        "Song: DEAF KEV - Invincible [NCS Release]\nMusic provided by NoCopyrightSounds\nFree Download: http://ncs.io",
    ),
    (
        "Heroes Tonight",
        "Janji",
        ["Progressive House"],
        "NCS License",
        "heroes-tonight-janji.jpg",
        "heroes-tonight-janji.mp3",
        208,
        8338175,
        False,
        True,
        False,
        0,
        "Song: Janji - Heroes Tonight (feat. Johnning) [NCS Release]\nMusic provided by NoCopyrightSounds\nFree Download: http://ncs.io",
    ),
    (
        "Symbolism",
        "Electro-Light",
        ["Trap", "Electronic"],
        "NCS License",
        "symbolism-trilogy.jpg",
        "symbolism-electro-light.mp3",
        291,
        8738612,
        True,
        True,
        False,
        0,
        "Song: Electro-Light - Symbolism [NCS Release]\nMusic provided by NoCopyrightSounds\nFree Download: http://ncs.io",
    ),
    (
        "Symbolism Pt. II",
        "Electro-Light",
        ["Trap", "Electronic"],
        "NCS License",
        "symbolism-pt-2-electro-light.jpg",
        "symbolism-pt-2-electro-light.mp3",
        251,
        8234072,
        True,
        True,
        False,
        0,
        "Song: Electro-Light - Symbolism Pt. II [NCS Release]\nMusic provided by NoCopyrightSounds\nFree Download: http://ncs.io",
    ),
    (
        "Symbolism Pt. III",
        "Electro-Light",
        ["Trap", "Electronic"],
        "NCS License",
        "symbolism-pt-3-electro-light.jpg",
        "symbolism-pt-3-electro-light.mp3",
        247,
        7873460,
        True,
        True,
        False,
        0,
        "Song: Electro-Light - Symbolism Pt. III [NCS Release]\nMusic provided by NoCopyrightSounds\nFree Download: http://ncs.io",
    ),
    (
        "Blank",
        "Disfigure",
        ["Melodic Dubstep", "Electronic"],
        "NCS License",
        "blank-disfigure.jpg",
        "blank-disfigure.mp3",
        209,
        3346692,
        True,
        True,
        False,
        0,
        "Song: Disfigure - Blank [NCS Release]\nMusic provided by NoCopyrightSounds\nFree Download: http://ncs.io",
    ),
    (
        "Sky High",
        "Elektronomia",
        ["Progressive House", "Electronic"],
        "NCS License",
        "sky-high-elektronomia.jpg",
        "sky-high-elektronomia.mp3",
        236,
        9452217,
        True,
        True,
        False,
        0,
        "Song: Elektronomia - Sky High [NCS Release]\nMusic provided by NoCopyrightSounds\nFree Download: http://ncs.io",
    ),
    (
        "Sunburst",
        "Tobu",
        ["House", "Electronic"],
        "NCS License",
        "sunburst-tobu-itro.jpg",
        "sunburst-tobu-itro.mp3",
        190,
        4562998,
        True,
        True,
        False,
        0,
        "Song: Tobu & Itro - Sunburst [NCS Release]\nMusic provided by NoCopyrightSounds\nFree Download: http://ncs.io",
    ),
    (
        "Skyline",
        "Kovan",
        ["Progressive House", "Electronic"],
        "NCS License",
        "skyline-kovan-electro-light.jpg",
        "skyline-kovan-electro-light.mp3",
        230,
        9339510,
        True,
        True,
        False,
        0,
        "Song: Kovan & Electro-Light - Skyline [NCS Release]\nMusic provided by NoCopyrightSounds\nFree Download: http://ncs.io",
    ),
    (
        "Nova",
        "Ahrix",
        ["Electro House", "Electronic"],
        "NCS License",
        "nova-ahrix.jpg",
        "nova-ahrix.mp3",
        281,
        11258413,
        True,
        True,
        False,
        0,
        "Song: Ahrix - Nova [NCS Release]\nMusic provided by NoCopyrightSounds\nFree Download: http://ncs.io",
    ),
    (
        "Return to the Wild",
        "Tobu",
        ["House", "Chill"],
        "NCS License",
        "return-to-the-wild-tobu.jpg",
        "return-to-the-wild-tobu.mp3",
        198,
        6345534,
        True,
        True,
        False,
        0,
        "Song: Tobu - Return To The Wild [NCS Release]\nMusic provided by NoCopyrightSounds\nFree Download: http://ncs.io",
    ),
    (
        "My Heart",
        "Different Heaven",
        ["Drumstep", "Electronic"],
        "NCS License",
        "my-heart-different-heaven-ehide.jpg",
        "my-heart-different-heaven-ehide.mp3",
        267,
        4271541,
        True,
        True,
        False,
        0,
        "Song: Different Heaven & EH!DE - My Heart [NCS Release]\nMusic provided by NoCopyrightSounds\nFree Download: http://ncs.io",
    ),
    (
        "Monkeys Spinning Monkeys",
        "Kevin MacLeod",
        ["Comedy"],
        "CC BY 4.0",
        "",
        "monkeys-spinning-monkeys-kevin-macleod.mp3",
        125,
        5005207,
        True,
        True,
        False,
        0,
        '"Monkeys Spinning Monkeys" Kevin MacLeod (incompetech.com)\nLicensed under Creative Commons: By Attribution 4.0 License\nhttp://creativecommons.org/licenses/by/4.0/',
    ),
    (
        "Sneaky Snitch",
        "Kevin MacLeod",
        ["Comedy"],
        "CC BY 4.0",
        "",
        "sneaky-snitch-kevin-macleod.mp3",
        137,
        5466943,
        True,
        True,
        False,
        0,
        '"Sneaky Snitch" Kevin MacLeod (incompetech.com)\nLicensed under Creative Commons: By Attribution 4.0 License\nhttp://creativecommons.org/licenses/by/4.0/',
    ),
    (
        "Carefree",
        "Kevin MacLeod",
        ["Comedy", "Easy Listening"],
        "CC BY 4.0",
        "",
        "carefree-kevin-macleod.mp3",
        205,
        6566713,
        True,
        True,
        False,
        0,
        '"Carefree" Kevin MacLeod (incompetech.com)\nLicensed under Creative Commons: By Attribution 4.0 License\nhttp://creativecommons.org/licenses/by/4.0/',
    ),
    (
        "Fluffing a Duck",
        "Kevin MacLeod",
        ["Comedy"],
        "CC BY 4.0",
        "",
        "fluffing-a-duck-kevin-macleod.mp3",
        67,
        2696840,
        True,
        True,
        False,
        0,
        '"Fluffing a Duck" Kevin MacLeod (incompetech.com)\nLicensed under Creative Commons: By Attribution 4.0 License\nhttp://creativecommons.org/licenses/by/4.0/',
    ),
    (
        "Electrodoodle",
        "Kevin MacLeod",
        ["Electronic"],
        "CC BY 4.0",
        "",
        "electrodoodle-kevin-macleod.mp3",
        166,
        6644624,
        True,
        True,
        False,
        0,
        '"Electrodoodle" Kevin MacLeod (incompetech.com)\nLicensed under Creative Commons: By Attribution 4.0 License\nhttp://creativecommons.org/licenses/by/4.0/',
    ),
    (
        "Local Forecast - Elevator",
        "Kevin MacLeod",
        ["Easy Listening", "Jazz"],
        "CC BY 4.0",
        "",
        "local-forecast-kevin-macleod.mp3",
        165,
        6611177,
        True,
        True,
        False,
        0,
        '"Local Forecast - Elevator" Kevin MacLeod (incompetech.com)\nLicensed under Creative Commons: By Attribution 4.0 License\nhttp://creativecommons.org/licenses/by/4.0/',
    ),
    (
        "Wallpaper",
        "Kevin MacLeod",
        ["Electronic", "Chill"],
        "CC BY 4.0",
        "",
        "wallpaper-kevin-macleod.mp3",
        220,
        8804339,
        True,
        True,
        False,
        0,
        '"Wallpaper" Kevin MacLeod (incompetech.com)\nLicensed under Creative Commons: By Attribution 4.0 License\nhttp://creativecommons.org/licenses/by/4.0/',
    ),
    (
        "Life of Riley",
        "Kevin MacLeod",
        ["Rock", "Electronic"],
        "CC BY 4.0",
        "",
        "life-of-riley-kevin-macleod.mp3",
        235,
        7533831,
        True,
        True,
        False,
        0,
        '"Life of Riley" Kevin MacLeod (incompetech.com)\nLicensed under Creative Commons: By Attribution 4.0 License\nhttp://creativecommons.org/licenses/by/4.0/',
    ),
    (
        "Screen Saver",
        "Kevin MacLeod",
        ["Electronic"],
        "CC BY 4.0",
        "",
        "screen-saver-kevin-macleod.mp3",
        185,
        7417751,
        True,
        True,
        False,
        0,
        '"Screen Saver" Kevin MacLeod (incompetech.com)\nLicensed under Creative Commons: By Attribution 4.0 License\nhttp://creativecommons.org/licenses/by/4.0/',
    ),
    (
        "Darkest Child",
        "Kevin MacLeod",
        ["Rock", "Orchestral"],
        "CC BY 4.0",
        "",
        "darkest-child-kevin-macleod.mp3",
        239,
        9551329,
        True,
        True,
        False,
        0,
        '"Darkest Child" Kevin MacLeod (incompetech.com)\nLicensed under Creative Commons: By Attribution 4.0 License\nhttp://creativecommons.org/licenses/by/4.0/',
    ),
    (
        "Jaunty Gumption",
        "Kevin MacLeod",
        ["Comedy", "Jazz"],
        "CC BY 4.0",
        "",
        "jaunty-gumption-kevin-macleod.mp3",
        118,
        4738790,
        True,
        True,
        False,
        0,
        '"Jaunty Gumption" Kevin MacLeod (incompetech.com)\nLicensed under Creative Commons: By Attribution 4.0 License\nhttp://creativecommons.org/licenses/by/4.0/',
    ),
    (
        "Sardana",
        "Kevin MacLeod",
        ["Orchestral", "Jazz"],
        "CC BY 4.0",
        "",
        "sardana-kevin-macleod.mp3",
        192,
        6149590,
        True,
        True,
        False,
        0,
        '"Sardana" Kevin MacLeod (incompetech.com)\nLicensed under Creative Commons: By Attribution 4.0 License\nhttp://creativecommons.org/licenses/by/4.0/',
    ),
    (
        "Snowfall Intro",
        "Kai Engel",
        ["Ambient", "Neoclassical"],
        "CC BY 3.0",
        "chapter-one-cold-kai-engel.jpg",
        "snowfall-intro-kai-engel.mp3",
        441,
        17733223,
        True,
        True,
        False,
        0,
        '"Snowfall Intro" by Kai Engel (freemusicarchive.org)\nLicensed under CC BY 3.0: https://creativecommons.org/licenses/by/3.0/',
    ),
    (
        "December",
        "Kai Engel",
        ["Ambient", "Neoclassical"],
        "CC BY 3.0",
        "chapter-one-cold-kai-engel.jpg",
        "december-kai-engel.mp3",
        230,
        9274774,
        True,
        True,
        False,
        0,
        '"December" by Kai Engel (freemusicarchive.org)\nLicensed under CC BY 3.0: https://creativecommons.org/licenses/by/3.0/',
    ),
    (
        "Blizzard PON I",
        "Kai Engel",
        ["Ambient", "Neoclassical"],
        "CC BY 3.0",
        "chapter-one-cold-kai-engel.jpg",
        "blizzard-pon-1-kai-engel.mp3",
        182,
        7373059,
        True,
        True,
        False,
        0,
        '"Blizzard PON I" by Kai Engel (freemusicarchive.org)\nLicensed under CC BY 3.0: https://creativecommons.org/licenses/by/3.0/',
    ),
    (
        "Snowmen",
        "Kai Engel",
        ["Ambient", "Neoclassical"],
        "CC BY 3.0",
        "chapter-one-cold-kai-engel.jpg",
        "snowmen-kai-engel.mp3",
        103,
        4217468,
        True,
        True,
        False,
        0,
        '"Snowmen" by Kai Engel (freemusicarchive.org)\nLicensed under CC BY 3.0: https://creativecommons.org/licenses/by/3.0/',
    ),
    (
        "January",
        "Kai Engel",
        ["Ambient", "Neoclassical"],
        "CC BY 3.0",
        "chapter-one-cold-kai-engel.jpg",
        "january-kai-engel.mp3",
        155,
        6305174,
        True,
        True,
        False,
        0,
        '"January" by Kai Engel (freemusicarchive.org)\nLicensed under CC BY 3.0: https://creativecommons.org/licenses/by/3.0/',
    ),
    (
        "Morbid Imagination",
        "Kai Engel",
        ["Ambient", "Neoclassical"],
        "CC BY 3.0",
        "chapter-one-cold-kai-engel.jpg",
        "morbid-imagination-kai-engel.mp3",
        191,
        7719966,
        True,
        True,
        False,
        0,
        '"Morbid Imagination" by Kai Engel (freemusicarchive.org)\nLicensed under CC BY 3.0: https://creativecommons.org/licenses/by/3.0/',
    ),
    (
        "February",
        "Kai Engel",
        ["Ambient", "Neoclassical"],
        "CC BY 3.0",
        "chapter-one-cold-kai-engel.jpg",
        "february-kai-engel.mp3",
        135,
        5495378,
        True,
        True,
        False,
        0,
        '"February" by Kai Engel (freemusicarchive.org)\nLicensed under CC BY 3.0: https://creativecommons.org/licenses/by/3.0/',
    ),
    (
        "Thaw Outro",
        "Kai Engel",
        ["Ambient", "Neoclassical"],
        "CC BY 3.0",
        "chapter-one-cold-kai-engel.jpg",
        "thaw-outro-kai-engel.mp3",
        118,
        4803655,
        True,
        True,
        False,
        0,
        '"Thaw Outro" by Kai Engel (freemusicarchive.org)\nLicensed under CC BY 3.0: https://creativecommons.org/licenses/by/3.0/',
    ),
    (
        "Nothing (Bonus Track)",
        "Kai Engel",
        ["Ambient", "Neoclassical"],
        "CC BY 3.0",
        "chapter-one-cold-kai-engel.jpg",
        "nothing-bonus-kai-engel.mp3",
        292,
        11785664,
        True,
        True,
        False,
        0,
        '"Nothing (Bonus Track)" by Kai Engel (freemusicarchive.org)\nLicensed under CC BY 3.0: https://creativecommons.org/licenses/by/3.0/',
    ),
    (
        "Floret",
        "Kai Engel",
        ["Ambient", "Neoclassical"],
        "CC BY 3.0",
        "chapter-two-mild-kai-engel.jpg",
        "floret-kai-engel.mp3",
        282,
        11442561,
        True,
        True,
        False,
        0,
        '"Floret" by Kai Engel (freemusicarchive.org)\nLicensed under CC BY 3.0: https://creativecommons.org/licenses/by/3.0/',
    ),
    (
        "March",
        "Kai Engel",
        ["Ambient", "Neoclassical"],
        "CC BY 3.0",
        "chapter-two-mild-kai-engel.jpg",
        "march-kai-engel.mp3",
        145,
        5963116,
        True,
        True,
        False,
        0,
        '"March" by Kai Engel (freemusicarchive.org)\nLicensed under CC BY 3.0: https://creativecommons.org/licenses/by/3.0/',
    ),
    (
        "Brooks",
        "Kai Engel",
        ["Ambient", "Neoclassical"],
        "CC BY 3.0",
        "chapter-two-mild-kai-engel.jpg",
        "brooks-kai-engel.mp3",
        128,
        5299606,
        True,
        True,
        False,
        0,
        '"Brooks" by Kai Engel (freemusicarchive.org)\nLicensed under CC BY 3.0: https://creativecommons.org/licenses/by/3.0/',
    ),
    (
        "River",
        "Kai Engel",
        ["Ambient", "Neoclassical"],
        "CC BY 3.0",
        "chapter-two-mild-kai-engel.jpg",
        "river-kai-engel.mp3",
        174,
        7138626,
        True,
        True,
        False,
        0,
        '"River" by Kai Engel (freemusicarchive.org)\nLicensed under CC BY 3.0: https://creativecommons.org/licenses/by/3.0/',
    ),
    (
        "April",
        "Kai Engel",
        ["Ambient", "Neoclassical"],
        "CC BY 3.0",
        "chapter-two-mild-kai-engel.jpg",
        "april-kai-engel.mp3",
        146,
        5999687,
        True,
        True,
        False,
        0,
        '"April" by Kai Engel (freemusicarchive.org)\nLicensed under CC BY 3.0: https://creativecommons.org/licenses/by/3.0/',
    ),
    (
        "Daylight PON II",
        "Kai Engel",
        ["Ambient", "Neoclassical"],
        "CC BY 3.0",
        "chapter-two-mild-kai-engel.jpg",
        "daylight-pon-2-kai-engel.mp3",
        198,
        8070675,
        True,
        True,
        False,
        0,
        '"Daylight PON II" by Kai Engel (freemusicarchive.org)\nLicensed under CC BY 3.0: https://creativecommons.org/licenses/by/3.0/',
    ),
    (
        "May",
        "Kai Engel",
        ["Ambient", "Neoclassical"],
        "CC BY 3.0",
        "chapter-two-mild-kai-engel.jpg",
        "may-kai-engel.mp3",
        133,
        5470969,
        True,
        True,
        False,
        0,
        '"May" by Kai Engel (freemusicarchive.org)\nLicensed under CC BY 3.0: https://creativecommons.org/licenses/by/3.0/',
    ),
    (
        "The Blossom PON III",
        "Kai Engel",
        ["Ambient", "Neoclassical"],
        "CC BY 3.0",
        "chapter-two-mild-kai-engel.jpg",
        "the-blossom-pon-3-kai-engel.mp3",
        169,
        6917108,
        True,
        True,
        False,
        0,
        '"The Blossom PON III" by Kai Engel (freemusicarchive.org)\nLicensed under CC BY 3.0: https://creativecommons.org/licenses/by/3.0/',
    ),
    (
        "Something (Bonus Track)",
        "Kai Engel",
        ["Ambient", "Neoclassical"],
        "CC BY 3.0",
        "chapter-two-mild-kai-engel.jpg",
        "something-bonus-kai-engel.mp3",
        271,
        11003704,
        True,
        True,
        False,
        0,
        '"Something (Bonus Track)" by Kai Engel (freemusicarchive.org)\nLicensed under CC BY 3.0: https://creativecommons.org/licenses/by/3.0/',
    ),
    (
        "Cloudburst",
        "Kai Engel",
        ["Ambient", "Neoclassical"],
        "CC BY 3.0",
        "chapter-three-warm-kai-engel.jpg",
        "cloudburst-kai-engel.mp3",
        181,
        7325036,
        True,
        True,
        False,
        0,
        '"Cloudburst" by Kai Engel (freemusicarchive.org)\nLicensed under CC BY 3.0: https://creativecommons.org/licenses/by/3.0/',
    ),
    (
        "June",
        "Kai Engel",
        ["Ambient", "Neoclassical"],
        "CC BY 3.0",
        "chapter-three-warm-kai-engel.jpg",
        "june-kai-engel.mp3",
        139,
        5636481,
        True,
        True,
        False,
        0,
        '"June" by Kai Engel (freemusicarchive.org)\nLicensed under CC BY 3.0: https://creativecommons.org/licenses/by/3.0/',
    ),
    (
        "Sunray PON IV",
        "Kai Engel",
        ["Ambient", "Neoclassical"],
        "CC BY 3.0",
        "chapter-three-warm-kai-engel.jpg",
        "sunray-pon-4-kai-engel.mp3",
        120,
        4890424,
        True,
        True,
        False,
        0,
        '"Sunray PON IV" by Kai Engel (freemusicarchive.org)\nLicensed under CC BY 3.0: https://creativecommons.org/licenses/by/3.0/',
    ),
    (
        "Shinedown PON V",
        "Kai Engel",
        ["Ambient", "Neoclassical"],
        "CC BY 3.0",
        "chapter-three-warm-kai-engel.jpg",
        "shinedown-pon-5-kai-engel.mp3",
        180,
        7308318,
        True,
        True,
        False,
        0,
        '"Shinedown PON V" by Kai Engel (freemusicarchive.org)\nLicensed under CC BY 3.0: https://creativecommons.org/licenses/by/3.0/',
    ),
    (
        "July",
        "Kai Engel",
        ["Ambient", "Neoclassical"],
        "CC BY 3.0",
        "chapter-three-warm-kai-engel.jpg",
        "july-kai-engel.mp3",
        220,
        8874620,
        True,
        True,
        False,
        0,
        '"July" by Kai Engel (freemusicarchive.org)\nLicensed under CC BY 3.0: https://creativecommons.org/licenses/by/3.0/',
    ),
    (
        "Rainbow PON VI",
        "Kai Engel",
        ["Ambient", "Neoclassical"],
        "CC BY 3.0",
        "chapter-three-warm-kai-engel.jpg",
        "rainbow-pon-6-kai-engel.mp3",
        143,
        5798440,
        True,
        True,
        False,
        0,
        '"Rainbow PON VI" by Kai Engel (freemusicarchive.org)\nLicensed under CC BY 3.0: https://creativecommons.org/licenses/by/3.0/',
    ),
    (
        "August Summer Nights",
        "Kai Engel",
        ["Ambient", "Neoclassical"],
        "CC BY 3.0",
        "chapter-three-warm-kai-engel.jpg",
        "august-summer-nights-kai-engel.mp3",
        105,
        4274979,
        True,
        True,
        False,
        0,
        '"August Summer Nights" by Kai Engel (freemusicarchive.org)\nLicensed under CC BY 3.0: https://creativecommons.org/licenses/by/3.0/',
    ),
    (
        "Far From Home PON VII",
        "Kai Engel",
        ["Ambient", "Neoclassical"],
        "CC BY 3.0",
        "chapter-three-warm-kai-engel.jpg",
        "far-from-home-pon-7-kai-engel.mp3",
        139,
        5637526,
        True,
        True,
        False,
        0,
        '"Far From Home PON VII" by Kai Engel (freemusicarchive.org)\nLicensed under CC BY 3.0: https://creativecommons.org/licenses/by/3.0/',
    ),
    (
        "Walking Barefoot on Grass (Bonus)",
        "Kai Engel",
        ["Ambient", "Neoclassical"],
        "CC BY 3.0",
        "chapter-three-warm-kai-engel.jpg",
        "walking-barefoot-on-grass-kai-engel.mp3",
        133,
        5424367,
        True,
        True,
        False,
        0,
        '"Walking Barefoot on Grass" by Kai Engel (freemusicarchive.org)\nLicensed under CC BY 3.0: https://creativecommons.org/licenses/by/3.0/',
    ),
    (
        "Night Owl",
        "Broke For Free",
        ["Chill", "Instrumental Hip-Hop"],
        "CC BY 3.0",
        "directionless-ep-broke-for-free.jpg",
        "night-owl-broke-for-free.mp3",
        194,
        8054458,
        True,
        True,
        False,
        0,
        '"Night Owl" by Broke For Free (freemusicarchive.org)\nLicensed under CC BY 3.0: https://creativecommons.org/licenses/by/3.0/',
    ),
    (
        "My Always Mood",
        "Broke For Free",
        ["Chill", "Instrumental Hip-Hop"],
        "CC BY 3.0",
        "directionless-ep-broke-for-free.jpg",
        "my-always-mood-broke-for-free.mp3",
        189,
        7833985,
        True,
        True,
        False,
        0,
        '"My Always Mood" by Broke For Free (freemusicarchive.org)\nLicensed under CC BY 3.0: https://creativecommons.org/licenses/by/3.0/',
    ),
    (
        "Day Bird",
        "Broke For Free",
        ["Chill", "Instrumental Hip-Hop"],
        "CC BY 3.0",
        "directionless-ep-broke-for-free.jpg",
        "day-bird-broke-for-free.mp3",
        223,
        9221609,
        True,
        True,
        False,
        0,
        '"Day Bird" by Broke For Free (freemusicarchive.org)\nLicensed under CC BY 3.0: https://creativecommons.org/licenses/by/3.0/',
    ),
    (
        "My Luck",
        "Broke For Free",
        ["Chill", "Instrumental Hip-Hop"],
        "CC BY 3.0",
        "directionless-ep-broke-for-free.jpg",
        "my-luck-broke-for-free.mp3",
        323,
        13204760,
        True,
        True,
        False,
        0,
        '"My Luck" by Broke For Free (freemusicarchive.org)\nLicensed under CC BY 3.0: https://creativecommons.org/licenses/by/3.0/',
    ),
    (
        "Mells Parade",
        "Broke For Free",
        ["Chill", "Instrumental Hip-Hop"],
        "CC BY 3.0",
        "directionless-ep-broke-for-free.jpg",
        "mells-parade-broke-for-free.mp3",
        198,
        8215373,
        True,
        True,
        False,
        0,
        '"Mells Parade" by Broke For Free (freemusicarchive.org)\nLicensed under CC BY 3.0: https://creativecommons.org/licenses/by/3.0/',
    ),
    (
        "Only Instrumental",
        "Broke For Free",
        ["Chill", "Instrumental Hip-Hop"],
        "CC BY 3.0",
        "directionless-ep-broke-for-free.jpg",
        "only-instrumental-broke-for-free.mp3",
        159,
        6635487,
        True,
        True,
        False,
        0,
        '"Only Instrumental" by Broke For Free (freemusicarchive.org)\nLicensed under CC BY 3.0: https://creativecommons.org/licenses/by/3.0/',
    ),
    (
        "Nothing Like Captain Crunch",
        "Broke For Free",
        ["Funk", "Electronic"],
        "CC BY 3.0",
        "slam-funk-broke-for-free.jpg",
        "nothing-like-captain-crunch-broke-for-free.mp3",
        310,
        12702123,
        True,
        True,
        False,
        0,
        '"Nothing Like Captain Crunch" by Broke For Free (freemusicarchive.org)\nLicensed under CC BY 3.0: https://creativecommons.org/licenses/by/3.0/',
    ),
    (
        "Calm The Fuck Down",
        "Broke For Free",
        ["Funk", "Electronic"],
        "CC BY 3.0",
        "slam-funk-broke-for-free.jpg",
        "calm-the-f-down-broke-for-free.mp3",
        275,
        11307184,
        True,
        True,
        False,
        0,
        '"Calm The Fuck Down" by Broke For Free (freemusicarchive.org)\nLicensed under CC BY 3.0: https://creativecommons.org/licenses/by/3.0/',
    ),
    (
        "The Great",
        "Broke For Free",
        ["Funk", "Electronic"],
        "CC BY 3.0",
        "slam-funk-broke-for-free.jpg",
        "the-great-broke-for-free.mp3",
        357,
        14569355,
        True,
        True,
        False,
        0,
        '"The Great" by Broke For Free (freemusicarchive.org)\nLicensed under CC BY 3.0: https://creativecommons.org/licenses/by/3.0/',
    ),
    (
        "Caught In The Beat",
        "Broke For Free",
        ["Funk", "Electronic"],
        "CC BY 3.0",
        "slam-funk-broke-for-free.jpg",
        "caught-in-the-beat-broke-for-free.mp3",
        263,
        10803543,
        True,
        True,
        False,
        0,
        '"Caught In The Beat" by Broke For Free (freemusicarchive.org)\nLicensed under CC BY 3.0: https://creativecommons.org/licenses/by/3.0/',
    ),
    (
        "Hella",
        "Broke For Free",
        ["Funk", "Electronic"],
        "CC BY 3.0",
        "slam-funk-broke-for-free.jpg",
        "hella-broke-for-free.mp3",
        269,
        11037600,
        True,
        True,
        False,
        0,
        '"Hella" by Broke For Free (freemusicarchive.org)\nLicensed under CC BY 3.0: https://creativecommons.org/licenses/by/3.0/',
    ),
    (
        "High School Snaps",
        "Broke For Free",
        ["Funk", "Electronic"],
        "CC BY 3.0",
        "slam-funk-broke-for-free.jpg",
        "high-school-snaps-broke-for-free.mp3",
        271,
        11151494,
        True,
        True,
        False,
        0,
        '"High School Snaps" by Broke For Free (freemusicarchive.org)\nLicensed under CC BY 3.0: https://creativecommons.org/licenses/by/3.0/',
    ),
    (
        "At The Count",
        "Broke For Free",
        ["Funk", "Electronic"],
        "CC BY 3.0",
        "slam-funk-broke-for-free.jpg",
        "at-the-count-broke-for-free.mp3",
        247,
        10158841,
        True,
        True,
        False,
        0,
        '"At The Count" by Broke For Free (freemusicarchive.org)\nLicensed under CC BY 3.0: https://creativecommons.org/licenses/by/3.0/',
    ),
    (
        "Living In Reverse",
        "Broke For Free",
        ["Funk", "Electronic"],
        "CC BY 3.0",
        "slam-funk-broke-for-free.jpg",
        "living-in-reverse-broke-for-free.mp3",
        208,
        8614482,
        True,
        True,
        False,
        0,
        '"Living In Reverse" by Broke For Free (freemusicarchive.org)\nLicensed under CC BY 3.0: https://creativecommons.org/licenses/by/3.0/',
    ),
    (
        "Drop of Water In the Ocean",
        "Broke For Free",
        ["Funk", "Electronic"],
        "CC BY 3.0",
        "slam-funk-broke-for-free.jpg",
        "drop-of-water-in-the-ocean-broke-for-free.mp3",
        297,
        12152506,
        True,
        True,
        False,
        0,
        '"Drop of Water In the Ocean" by Broke For Free (freemusicarchive.org)\nLicensed under CC BY 3.0: https://creativecommons.org/licenses/by/3.0/',
    ),
    (
        "Covered In Oil",
        "Broke For Free",
        ["Funk", "Electronic"],
        "CC BY 3.0",
        "slam-funk-broke-for-free.jpg",
        "covered-in-oil-broke-for-free.mp3",
        256,
        10514106,
        True,
        True,
        False,
        0,
        '"Covered In Oil" by Broke For Free (freemusicarchive.org)\nLicensed under CC BY 3.0: https://creativecommons.org/licenses/by/3.0/',
    ),
    (
        "Simple Hop",
        "Broke For Free",
        ["Funk", "Electronic"],
        "CC BY 3.0",
        "slam-funk-broke-for-free.jpg",
        "simple-hop-broke-for-free.mp3",
        307,
        12561061,
        True,
        True,
        False,
        0,
        '"Simple Hop" by Broke For Free (freemusicarchive.org)\nLicensed under CC BY 3.0: https://creativecommons.org/licenses/by/3.0/',
    ),
    (
        "Our Ego (Feat. Different Visitor)",
        "Broke For Free",
        ["Funk", "Electronic"],
        "CC BY 3.0",
        "slam-funk-broke-for-free.jpg",
        "our-ego-broke-for-free.mp3",
        335,
        13684327,
        True,
        True,
        False,
        0,
        '"Our Ego" by Broke For Free (freemusicarchive.org)\nLicensed under CC BY 3.0: https://creativecommons.org/licenses/by/3.0/',
    ),
    (
        "Children's TV",
        "Scott Holmes",
        ["Cinematic", "Soundtrack"],
        "CC BY 4.0",
        "music-for-media-1-scott-holmes.jpg",
        "childrens-tv-scott-holmes.mp3",
        62,
        993895,
        True,
        True,
        False,
        0,
        '"Children\'s TV" by Scott Holmes (freemusicarchive.org)\nLicensed under CC BY 4.0: https://creativecommons.org/licenses/by/4.0/',
    ),
    (
        "Everest",
        "Scott Holmes",
        ["Cinematic", "Soundtrack"],
        "CC BY 4.0",
        "music-for-media-1-scott-holmes.jpg",
        "everest-scott-holmes.mp3",
        137,
        2198035,
        True,
        True,
        False,
        0,
        '"Everest" by Scott Holmes (freemusicarchive.org)\nLicensed under CC BY 4.0: https://creativecommons.org/licenses/by/4.0/',
    ),
    (
        "Old Oak Tree",
        "Scott Holmes",
        ["Cinematic", "Soundtrack"],
        "CC BY 4.0",
        "music-for-media-1-scott-holmes.jpg",
        "old-oak-tree-scott-holmes.mp3",
        114,
        1827096,
        True,
        True,
        False,
        0,
        '"Old Oak Tree" by Scott Holmes (freemusicarchive.org)\nLicensed under CC BY 4.0: https://creativecommons.org/licenses/by/4.0/',
    ),
    (
        "Empires",
        "Scott Holmes",
        ["Cinematic", "Soundtrack"],
        "CC BY 4.0",
        "music-for-media-1-scott-holmes.jpg",
        "empires-scott-holmes.mp3",
        84,
        1349369,
        True,
        True,
        False,
        0,
        '"Empires" by Scott Holmes (freemusicarchive.org)\nLicensed under CC BY 4.0: https://creativecommons.org/licenses/by/4.0/',
    ),
    (
        "Moment Of Magic",
        "Scott Holmes",
        ["Cinematic", "Soundtrack"],
        "CC BY 4.0",
        "music-for-media-1-scott-holmes.jpg",
        "moment-of-magic-scott-holmes.mp3",
        107,
        1714038,
        True,
        True,
        False,
        0,
        '"Moment Of Magic" by Scott Holmes (freemusicarchive.org)\nLicensed under CC BY 4.0: https://creativecommons.org/licenses/by/4.0/',
    ),
    (
        "Ragnars Kingdom",
        "Scott Holmes",
        ["Cinematic", "Soundtrack"],
        "CC BY 4.0",
        "music-for-media-1-scott-holmes.jpg",
        "ragnars-kingdom-scott-holmes.mp3",
        151,
        2414538,
        True,
        True,
        False,
        0,
        '"Ragnars Kingdom" by Scott Holmes (freemusicarchive.org)\nLicensed under CC BY 4.0: https://creativecommons.org/licenses/by/4.0/',
    ),
    (
        "Vikings Are Coming",
        "Scott Holmes",
        ["Cinematic", "Soundtrack"],
        "CC BY 4.0",
        "music-for-media-1-scott-holmes.jpg",
        "vikings-are-coming-scott-holmes.mp3",
        132,
        2114025,
        True,
        True,
        False,
        0,
        '"Vikings Are Coming" by Scott Holmes (freemusicarchive.org)\nLicensed under CC BY 4.0: https://creativecommons.org/licenses/by/4.0/',
    ),
    (
        "Motivational",
        "Scott Holmes",
        ["Cinematic", "Electronic"],
        "CC BY 4.0",
        "music-for-tv-film-3-scott-holmes.jpg",
        "motivational-scott-holmes.mp3",
        182,
        7267182,
        True,
        True,
        False,
        0,
        '"Motivational" by Scott Holmes (freemusicarchive.org)\nLicensed under CC BY 4.0: https://creativecommons.org/licenses/by/4.0/',
    ),
    (
        "Reach For Success",
        "Scott Holmes",
        ["Cinematic", "Electronic"],
        "CC BY 4.0",
        "music-for-tv-film-3-scott-holmes.jpg",
        "reach-for-success-scott-holmes.mp3",
        117,
        4666431,
        True,
        True,
        False,
        0,
        '"Reach For Success" by Scott Holmes (freemusicarchive.org)\nLicensed under CC BY 4.0: https://creativecommons.org/licenses/by/4.0/',
    ),
    (
        "Follow Your Dreams",
        "Scott Holmes",
        ["Cinematic", "Electronic"],
        "CC BY 4.0",
        "music-for-tv-film-3-scott-holmes.jpg",
        "follow-your-dreams-scott-holmes.mp3",
        163,
        6526349,
        True,
        True,
        False,
        0,
        '"Follow Your Dreams" by Scott Holmes (freemusicarchive.org)\nLicensed under CC BY 4.0: https://creativecommons.org/licenses/by/4.0/',
    ),
    (
        "Kiss The Sky",
        "Scott Holmes",
        ["Cinematic", "Electronic"],
        "CC BY 4.0",
        "music-for-tv-film-3-scott-holmes.jpg",
        "kiss-the-sky-scott-holmes.mp3",
        182,
        7267182,
        True,
        True,
        False,
        0,
        '"Kiss The Sky" by Scott Holmes (freemusicarchive.org)\nLicensed under CC BY 4.0: https://creativecommons.org/licenses/by/4.0/',
    ),
    (
        "Big Apple",
        "Scott Holmes",
        ["Cinematic", "Electronic"],
        "CC BY 4.0",
        "music-for-tv-film-3-scott-holmes.jpg",
        "big-apple-scott-holmes.mp3",
        167,
        6664276,
        True,
        True,
        False,
        0,
        '"Big Apple" by Scott Holmes (freemusicarchive.org)\nLicensed under CC BY 4.0: https://creativecommons.org/licenses/by/4.0/',
    ),
    (
        "New Beginnings",
        "Scott Holmes",
        ["Cinematic", "Electronic"],
        "CC BY 4.0",
        "music-for-tv-film-3-scott-holmes.jpg",
        "new-beginnings-scott-holmes.mp3",
        144,
        5772978,
        True,
        True,
        False,
        0,
        '"New Beginnings" by Scott Holmes (freemusicarchive.org)\nLicensed under CC BY 4.0: https://creativecommons.org/licenses/by/4.0/',
    ),
    (
        "A New Day",
        "Scott Holmes",
        ["Cinematic", "Electronic"],
        "CC BY 4.0",
        "music-for-tv-film-3-scott-holmes.jpg",
        "a-new-day-scott-holmes.mp3",
        164,
        6545158,
        True,
        True,
        False,
        0,
        '"A New Day" by Scott Holmes (freemusicarchive.org)\nLicensed under CC BY 4.0: https://creativecommons.org/licenses/by/4.0/',
    ),
    (
        "Skip In My Step",
        "Scott Holmes",
        ["Cinematic", "Electronic"],
        "CC BY 4.0",
        "music-for-tv-film-3-scott-holmes.jpg",
        "skip-in-my-step-scott-holmes.mp3",
        108,
        2155541,
        True,
        True,
        False,
        0,
        '"Skip In My Step" by Scott Holmes (freemusicarchive.org)\nLicensed under CC BY 4.0: https://creativecommons.org/licenses/by/4.0/',
    ),
    (
        "Inspiring And Upbeat",
        "Scott Holmes",
        ["Cinematic", "Electronic"],
        "CC BY 4.0",
        "music-for-tv-film-3-scott-holmes.jpg",
        "inspiring-and-upbeat-scott-holmes.mp3",
        131,
        5246349,
        True,
        True,
        False,
        0,
        '"Inspiring And Upbeat" by Scott Holmes (freemusicarchive.org)\nLicensed under CC BY 4.0: https://creativecommons.org/licenses/by/4.0/',
    ),
    (
        "Remember Me",
        "Scott Holmes",
        ["Cinematic", "Electronic"],
        "CC BY 4.0",
        "music-for-tv-film-3-scott-holmes.jpg",
        "remember-me-scott-holmes.mp3",
        131,
        5237990,
        True,
        True,
        False,
        0,
        '"Remember Me" by Scott Holmes (freemusicarchive.org)\nLicensed under CC BY 4.0: https://creativecommons.org/licenses/by/4.0/',
    ),
    (
        "Play Time",
        "Scott Holmes",
        ["Cinematic", "Electronic"],
        "CC BY 4.0",
        "music-for-tv-film-3-scott-holmes.jpg",
        "play-time-scott-holmes.mp3",
        54,
        2146137,
        True,
        True,
        False,
        0,
        '"Play Time" by Scott Holmes (freemusicarchive.org)\nLicensed under CC BY 4.0: https://creativecommons.org/licenses/by/4.0/',
    ),
    (
        "March Of The Midnight Critters",
        "Scott Holmes",
        ["Cinematic", "Electronic"],
        "CC BY 4.0",
        "music-for-tv-film-3-scott-holmes.jpg",
        "march-of-the-midnight-critters-scott-holmes.mp3",
        135,
        5386366,
        True,
        True,
        False,
        0,
        '"March Of The Midnight Critters" by Scott Holmes (freemusicarchive.org)\nLicensed under CC BY 4.0: https://creativecommons.org/licenses/by/4.0/',
    ),
    (
        "Part I",
        "Jahzzar",
        ["Ambient", "Electronic"],
        "CC BY-SA 3.0",
        "moonxine-jahzzar.jpg",
        "moonxine-part-1-jahzzar.mp3",
        230,
        5391852,
        True,
        True,
        False,
        0,
        '"Part I" by Jahzzar (freemusicarchive.org)\nLicensed under CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/',
    ),
    (
        "Part II",
        "Jahzzar",
        ["Ambient", "Electronic"],
        "CC BY-SA 3.0",
        "moonxine-jahzzar.jpg",
        "moonxine-part-2-jahzzar.mp3",
        423,
        9854050,
        True,
        True,
        False,
        0,
        '"Part II" by Jahzzar (freemusicarchive.org)\nLicensed under CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/',
    ),
    (
        "Part III",
        "Jahzzar",
        ["Ambient", "Electronic"],
        "CC BY-SA 3.0",
        "moonxine-jahzzar.jpg",
        "moonxine-part-3-jahzzar.mp3",
        299,
        5809517,
        True,
        True,
        False,
        0,
        '"Part III" by Jahzzar (freemusicarchive.org)\nLicensed under CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/',
    ),
    (
        "Part IV",
        "Jahzzar",
        ["Ambient", "Electronic"],
        "CC BY-SA 3.0",
        "moonxine-jahzzar.jpg",
        "moonxine-part-4-jahzzar.mp3",
        287,
        7404848,
        True,
        True,
        False,
        0,
        '"Part IV" by Jahzzar (freemusicarchive.org)\nLicensed under CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/',
    ),
    (
        "Part V",
        "Jahzzar",
        ["Ambient", "Electronic"],
        "CC BY-SA 3.0",
        "moonxine-jahzzar.jpg",
        "moonxine-part-5-jahzzar.mp3",
        271,
        5786674,
        True,
        True,
        False,
        0,
        '"Part V" by Jahzzar (freemusicarchive.org)\nLicensed under CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/',
    ),
    (
        "Part VI",
        "Jahzzar",
        ["Ambient", "Electronic"],
        "CC BY-SA 3.0",
        "moonxine-jahzzar.jpg",
        "moonxine-part-6-jahzzar.mp3",
        404,
        8073156,
        True,
        True,
        False,
        0,
        '"Part VI" by Jahzzar (freemusicarchive.org)\nLicensed under CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/',
    ),
    (
        "Part VII",
        "Jahzzar",
        ["Ambient", "Electronic"],
        "CC BY-SA 3.0",
        "moonxine-jahzzar.jpg",
        "moonxine-part-7-jahzzar.mp3",
        146,
        3418245,
        True,
        True,
        False,
        0,
        '"Part VII" by Jahzzar (freemusicarchive.org)\nLicensed under CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/',
    ),
    (
        "Part VIII",
        "Jahzzar",
        ["Ambient", "Electronic"],
        "CC BY-SA 3.0",
        "moonxine-jahzzar.jpg",
        "moonxine-part-8-jahzzar.mp3",
        462,
        12724662,
        True,
        True,
        False,
        0,
        '"Part VIII" by Jahzzar (freemusicarchive.org)\nLicensed under CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/',
    ),
    (
        "Part IX",
        "Jahzzar",
        ["Ambient", "Electronic"],
        "CC BY-SA 3.0",
        "moonxine-jahzzar.jpg",
        "moonxine-part-9-jahzzar.mp3",
        277,
        4999666,
        True,
        True,
        False,
        0,
        '"Part IX" by Jahzzar (freemusicarchive.org)\nLicensed under CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/',
    ),
    (
        "Part X",
        "Jahzzar",
        ["Ambient", "Electronic"],
        "CC BY-SA 3.0",
        "moonxine-jahzzar.jpg",
        "moonxine-part-10-jahzzar.mp3",
        207,
        3656536,
        True,
        True,
        False,
        0,
        '"Part X" by Jahzzar (freemusicarchive.org)\nLicensed under CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/',
    ),
    (
        "Happy Holydays Dance",
        "Lobo Loco",
        ["Blues", "Folk"],
        "CC BY 3.0",
        "tunnel-games-lobo-loco.jpg",
        "happy-holydays-dance-lobo-loco.mp3",
        73,
        1777133,
        True,
        True,
        False,
        0,
        '"Happy Holydays Dance" by Lobo Loco (freemusicarchive.org)\nLicensed under CC BY 3.0: https://creativecommons.org/licenses/by/3.0/',
    ),
    (
        "Hopefully Love",
        "Lobo Loco",
        ["Blues", "Folk"],
        "CC BY 3.0",
        "tunnel-games-lobo-loco.jpg",
        "hopefully-love-lobo-loco.mp3",
        467,
        11229522,
        True,
        True,
        False,
        0,
        '"Hopefully Love" by Lobo Loco (freemusicarchive.org)\nLicensed under CC BY 3.0: https://creativecommons.org/licenses/by/3.0/',
    ),
    (
        "Angels Roadtrip",
        "Lobo Loco",
        ["Blues", "Folk"],
        "CC BY 3.0",
        "tunnel-games-lobo-loco.jpg",
        "angels-roadtrip-lobo-loco.mp3",
        229,
        5516803,
        True,
        True,
        False,
        0,
        '"Angels Roadtrip" by Lobo Loco (freemusicarchive.org)\nLicensed under CC BY 3.0: https://creativecommons.org/licenses/by/3.0/',
    ),
    (
        "Even to Lately",
        "Lobo Loco",
        ["Blues", "Folk"],
        "CC BY 3.0",
        "tunnel-games-lobo-loco.jpg",
        "even-to-lately-lobo-loco.mp3",
        186,
        4483816,
        True,
        True,
        False,
        0,
        '"Even to Lately" by Lobo Loco (freemusicarchive.org)\nLicensed under CC BY 3.0: https://creativecommons.org/licenses/by/3.0/',
    ),
    (
        "Dreamy Feets (Instrumental)",
        "Lobo Loco",
        ["Blues", "Folk"],
        "CC BY 3.0",
        "tunnel-games-lobo-loco.jpg",
        "dreamy-feets-lobo-loco.mp3",
        234,
        5638551,
        True,
        True,
        False,
        0,
        '"Dreamy Feets" by Lobo Loco (freemusicarchive.org)\nLicensed under CC BY 3.0: https://creativecommons.org/licenses/by/3.0/',
    ),
    (
        "End of the Clans",
        "Lobo Loco",
        ["Blues", "Folk"],
        "CC BY 3.0",
        "tunnel-games-lobo-loco.jpg",
        "end-of-the-clans-lobo-loco.mp3",
        258,
        6214646,
        True,
        True,
        False,
        0,
        '"End of the Clans" by Lobo Loco (freemusicarchive.org)\nLicensed under CC BY 3.0: https://creativecommons.org/licenses/by/3.0/',
    ),
    (
        "St Mary Lake Hut",
        "Lobo Loco",
        ["Blues", "Folk"],
        "CC BY 3.0",
        "tunnel-games-lobo-loco.jpg",
        "st-mary-lake-hut-lobo-loco.mp3",
        271,
        6543492,
        True,
        True,
        False,
        0,
        '"St Mary Lake Hut" by Lobo Loco (freemusicarchive.org)\nLicensed under CC BY 3.0: https://creativecommons.org/licenses/by/3.0/',
    ),
    (
        "Heartly (Harphversion)",
        "Lobo Loco",
        ["Blues", "Folk"],
        "CC BY 3.0",
        "tunnel-games-lobo-loco.jpg",
        "heartly-harphversion-lobo-loco.mp3",
        407,
        9796634,
        True,
        True,
        False,
        0,
        '"Heartly (Harphversion)" by Lobo Loco (freemusicarchive.org)\nLicensed under CC BY 3.0: https://creativecommons.org/licenses/by/3.0/',
    ),
    (
        "Dusty Mountians",
        "Lobo Loco",
        ["Blues", "Folk"],
        "CC BY 3.0",
        "tunnel-games-lobo-loco.jpg",
        "dusty-mountians-lobo-loco.mp3",
        235,
        5661763,
        True,
        True,
        False,
        0,
        '"Dusty Mountians" by Lobo Loco (freemusicarchive.org)\nLicensed under CC BY 3.0: https://creativecommons.org/licenses/by/3.0/',
    ),
    (
        "New Beginning",
        "Lobo Loco",
        ["Blues", "Folk"],
        "CC BY 3.0",
        "tunnel-games-lobo-loco.jpg",
        "new-beginning-lobo-loco.mp3",
        196,
        4737999,
        True,
        True,
        False,
        0,
        '"New Beginning" by Lobo Loco (freemusicarchive.org)\nLicensed under CC BY 3.0: https://creativecommons.org/licenses/by/3.0/',
    ),
    (
        "Settlers Caravan",
        "Lobo Loco",
        ["Blues", "Folk"],
        "CC BY 3.0",
        "tunnel-games-lobo-loco.jpg",
        "settlers-caravan-lobo-loco.mp3",
        291,
        7020912,
        True,
        True,
        False,
        0,
        '"Settlers Caravan" by Lobo Loco (freemusicarchive.org)\nLicensed under CC BY 3.0: https://creativecommons.org/licenses/by/3.0/',
    ),
    (
        "Hopeful after Broken Dreams",
        "Lobo Loco",
        ["Blues", "Folk"],
        "CC BY 3.0",
        "tunnel-games-lobo-loco.jpg",
        "hopeful-after-broken-dreams-lobo-loco.mp3",
        238,
        5745878,
        True,
        True,
        False,
        0,
        '"Hopeful after Broken Dreams" by Lobo Loco (freemusicarchive.org)\nLicensed under CC BY 3.0: https://creativecommons.org/licenses/by/3.0/',
    ),
    (
        "Red Mountians Intro",
        "Lobo Loco",
        ["Blues", "Folk"],
        "CC BY 3.0",
        "tunnel-games-lobo-loco.jpg",
        "red-mountians-intro-lobo-loco.mp3",
        67,
        1628405,
        True,
        True,
        False,
        0,
        '"Red Mountians Intro" by Lobo Loco (freemusicarchive.org)\nLicensed under CC BY 3.0: https://creativecommons.org/licenses/by/3.0/',
    ),
    (
        "You got my Jacket",
        "Lobo Loco",
        ["Blues", "Folk"],
        "CC BY 3.0",
        "tunnel-games-lobo-loco.jpg",
        "you-got-my-jacket-lobo-loco.mp3",
        210,
        5068726,
        True,
        True,
        False,
        0,
        '"You got my Jacket" by Lobo Loco (freemusicarchive.org)\nLicensed under CC BY 3.0: https://creativecommons.org/licenses/by/3.0/',
    ),
    (
        "No More Blood",
        "Lobo Loco",
        ["Blues", "Folk"],
        "CC BY 3.0",
        "tunnel-games-lobo-loco.jpg",
        "no-more-blood-lobo-loco.mp3",
        263,
        6340786,
        True,
        True,
        False,
        0,
        '"No More Blood" by Lobo Loco (freemusicarchive.org)\nLicensed under CC BY 3.0: https://creativecommons.org/licenses/by/3.0/',
    ),
    (
        "Red Mountians",
        "Lobo Loco",
        ["Blues", "Folk"],
        "CC BY 3.0",
        "tunnel-games-lobo-loco.jpg",
        "red-mountians-lobo-loco.mp3",
        368,
        8854190,
        True,
        True,
        False,
        0,
        '"Red Mountians" by Lobo Loco (freemusicarchive.org)\nLicensed under CC BY 3.0: https://creativecommons.org/licenses/by/3.0/',
    ),
    (
        "Top of the Mountains",
        "Lobo Loco",
        ["Blues", "Folk"],
        "CC BY 3.0",
        "tunnel-games-lobo-loco.jpg",
        "top-of-the-mountains-lobo-loco.mp3",
        217,
        5240670,
        True,
        True,
        False,
        0,
        '"Top of the Mountains" by Lobo Loco (freemusicarchive.org)\nLicensed under CC BY 3.0: https://creativecommons.org/licenses/by/3.0/',
    ),
    (
        "Crazy Visions",
        "Lobo Loco",
        ["Blues", "Folk"],
        "CC BY 3.0",
        "tunnel-games-lobo-loco.jpg",
        "crazy-visions-lobo-loco.mp3",
        168,
        4047041,
        True,
        True,
        False,
        0,
        '"Crazy Visions" by Lobo Loco (freemusicarchive.org)\nLicensed under CC BY 3.0: https://creativecommons.org/licenses/by/3.0/',
    ),
]


class Command(BaseCommand):
    help = "Seed the catalog with demo data."

    def add_arguments(self, parser):
        parser.add_argument(
            "--fresh",
            action="store_true",
            help="Delete existing catalog data before seeding.",
        )

    def handle(self, *args, **options):

        if options["fresh"]:
            # FK-safe order: tracks reference everything, so they go first.
            Track.objects.all().delete()
            Artist.objects.all().delete()
            Genre.objects.all().delete()
            License.objects.all().delete()
            self.stdout.write("Wiped existing catalog data.")

        licenses = self._seed_licenses()
        genres = self._seed_genres()
        artists = self._seed_artists()
        self._seed_track(artists, genres, licenses)

        self.stdout.write(
            self.style.SUCCESS(
                f"Seeded: {License.objects.count()} licenses, {Genre.objects.count()} genres, "
                f"{Artist.objects.count()} artists, "
                f"{Track.objects.count()} tracks."
            )
        )

    # -- helpers ---------------------------------------------------------

    def _seed_licenses(self):
        out = {}
        for name, url, requires_attribution, description in LICENSES:
            obj, _ = License.objects.get_or_create(
                name=name,
                defaults={
                    "url": url,
                    "requires_attribution": requires_attribution,
                    "description": description,
                },
            )
            out[name] = obj
        return out

    def _seed_genres(self):
        out = {}
        for name in GENRES:
            obj, _ = Genre.objects.get_or_create(name=name)
            out[name] = obj
        return out

    def _seed_artists(self):
        out = {}
        for name, dob, bio in ARTISTS:
            obj, _ = Artist.objects.get_or_create(
                name=name,
                defaults={"dob": dob, "bio": bio},
            )
            out[name] = obj
        return out

    def _seed_track(self, artists, genres, licenses):
        out = {}
        for (
            title,
            artist_name,
            genre_names,
            license_name,
            cover,
            audio_file,
            duration_seconds,
            file_size,
            is_instrumental,
            is_published,
            is_private,
            play_count,
            attribution,
        ) in TRACKS:
            obj, _ = Track.objects.get_or_create(
                title=title,
                artist=artists[artist_name],
                defaults={
                    "license": licenses[license_name],
                    "cover": cover,
                    "audio_file": audio_file,
                    "duration_seconds": duration_seconds,
                    "file_size": file_size,
                    "is_instrumental": is_instrumental,
                    "is_published": is_published,
                    "is_private": is_private,
                    "play_count": play_count,
                    "attribution": attribution,
                },
            )
            obj.genres.set([genres[name] for name in genre_names])
            out[title] = obj
        return out
