# Generated by Django 6.1.1 on 2026-09-25 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artist",
            name="avatar",
            field=models.CharField(
                blank=True,
                help_text="A visual icon representing artist",
                max_length=255,
                verbose_name="Avatar",
            ),
        ),
        migrations.AlterField(
            model_name="license",
            name="url",
            field=models.URLField(
                blank=True,
                help_text="Canonical web page with the legal text of the license.",
                null=True,
                verbose_name="License URL",
            ),
        ),
    ]
