# Generated by Django 6.1.1 on 2026-09-27 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_artist_avatar_alter_license_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="track",
            name="cover",
            field=models.CharField(
                blank=True,
                default="cover-1bs02488.jpg",
                max_length=255,
                verbose_name="Cover art",
            ),
        ),
        migrations.AlterField(
            model_name="album",
            name="cover",
            field=models.CharField(
                blank=True,
                default="cover-1bs02488.jpg",
                max_length=255,
                verbose_name="Cover art",
            ),
        ),
        migrations.AlterField(
            model_name="artist",
            name="avatar",
            field=models.CharField(
                blank=True,
                help_text="A visual icon representing artist",
                max_length=255,
                null=True,
                verbose_name="Avatar",
            ),
        ),
        migrations.AlterField(
            model_name="license",
            name="name",
            field=models.CharField(
                choices=[
                    ("all_rights_reserved", "All Rights Reserved"),
                    ("public_domain", "Public Domain"),
                    ("cc0", "CC0"),
                    ("cc_by", "Creative Commons Attribution (CC BY)"),
                    ("cc_by_sa", "Creative Commons Attribution-ShareAlike (CC BY-SA)"),
                    (
                        "cc_by_nc",
                        "Creative Commons Attribution-NonCommercial (CC BY-NC)",
                    ),
                    (
                        "cc_by_nc_sa",
                        "Creative Commons Attribution-NonCommercial-ShareAlike (CC BY-NC-SA)",
                    ),
                    (
                        "cc_by_nd",
                        "Creative Commons Attribution-NoDerivatives (CC BY-ND)",
                    ),
                    (
                        "cc_by_nc_nd",
                        "Creative Commons Attribution-NonCommercial-NoDerivatives (CC BY-NC-ND)",
                    ),
                    ("royalty_free", "Royalty-Free"),
                    ("custom", "Custom"),
                ],
                default="all_rights_reserved",
                max_length=100,
                unique=True,
                verbose_name="License Name",
            ),
        ),
    ]
