# Generated by Django 6.1.1 on 2026-09-27 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_track_cover_alter_album_cover_alter_artist_avatar_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artist",
            name="avatar",
            field=models.CharField(
                blank=True,
                default="avatar-1bs02488.jpg",
                help_text="A visual icon representing artist",
                max_length=255,
                verbose_name="Avatar",
            ),
        ),
    ]
